Restore `list_artifacts` to its correct behavior (#811)
This fixes a regression from 384afee759351f22ab9e0a43ac066f3fa5f3b6d9
where `list_artifacts` went from listing the latest artifacts from a
task to getting the task definition and returning a non existent field
from it, leading to:

```
  File "/builds/worker/checkouts/src/taskcluster/src/target_tasks.py", line 27, in _filter_for_pr
    for artifact in list_artifacts(diff_task):
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/src/taskcluster-taskgraph/src/taskgraph/util/taskcluster.py", line 166, in list_artifacts
    return task["artifacts"]
           ~~~~^^^^^^^^^^^^^
KeyError: 'artifacts'
```